### ISSUE TITLE
Documentation of MariaDB image is missing / not helpful

### ISSUE THREAD

**Issue by bluenote10** [Websoft9/websoft9.github.io#1]
I tried to use [Websoft9's MariaDB Image from the Azure marketplace](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/websoft9inc.w9mariadb-ubuntu?tab=Overview). The marketplace page contains a link [MariaDB Image Guide](https://support.websoft9.com/docs/mysql), but that leads to a MySQL guide. I have a running VM now, and I can ssh into it, but I have no idea how the image is supposed to be used. The information I'm missing is e.g.:

- Do I have to launch anything in the image to start/stop the maria db server ? (similar to what is documented for the MySQL image)
- What is the default port / user / initial password for the DB?
- How to change the default password?

The MariaDB image would be much more accessible by adding some basic information to the marketplace page.

It is also not so helpful that the readme of this repository is in Chinese.

**Comment by chendelin1982** [comment]
We have created [MariaDB image guide](https://support.websoft9.com/docs/mariadb), thanks for your suggestion

**Comment by bluenote10** [comment]
@chendelin1982 Thanks for taking care of this.

What is a bit strange: If I click on the link you have posted it redirects me to `https://support.websoft9.com/docs/mysql` -- somewhat confusing, because that's the page that has caused me to open the issue ;). I had to edit the browser URL manually to `https://support.websoft9.com/docs/mariadb/` (note the trailing slash) to see the MariaDB image guide.
